# -*- coding: utf-8 -*-
"""
/***************************************************************************
 IndicesEspectrais
                                 A QGIS plugin
 Esse plugin calcula indices espectrais de um raster
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-09-11
        copyright            : (C) 2020 by Henrique Peschl/UFPR
        email                : henriquepeschl@ufpr.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load IndicesEspectrais class from file IndicesEspectrais.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .indices_espectrais import IndicesEspectrais
    return IndicesEspectrais(iface)
